"""
Django settings for tutorial project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv('SECRET_KEY', '')
# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.getenv('DEBUG', 'False') == 'True'
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    'oauth2_provider',
    "allauth.socialaccount.providers.google",
    'rest_framework_simplejwt',
    'quickstart',
    'django_filters',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tutorial.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tutorial.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Update database configuration for Render/Heroku
# Render automatically sets DATABASE_URL, Heroku uses the same
# db_from_env = dj_database_url.config(conn_max_age=600, ssl_require=True)
# if db_from_env:
#     DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OAUTH2_PROVIDER = {
    # this is the list of available scopes
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'}
}
REST_FRAMEWORK = {
    
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema'
}

AUTHENTICATION_BACKENDS = [         # default
    "allauth.account.auth_backends.AuthenticationBackend" # allauth
]

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Access token expires in 60 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # Refresh token expires in 1 day
    'ROTATE_REFRESH_TOKENS': True,                   # Rotate refresh token on each refresh
    'BLACKLIST_AFTER_ROTATION': True,                # Blacklist old tokens after rotation
    'UPDATE_LAST_LOGIN': True,                       # Update last login time
    
    'ALGORITHM': 'HS256',                            # Encryption algorithm
    'SIGNING_KEY': SECRET_KEY,                       # Signing key (uses Django SECRET_KEY)
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),                # Authorization header type
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',        # Authorization header name
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Your API',
    'DESCRIPTION': 'Your API description',
    'VERSION': '1.0.0',
}

SITE_ID = 1  # required by allauth Sites framework

# Get base URL from environment variable or use default
BASE_URL = os.getenv('BASE_URL', 'http://localhost:8000')
LOGIN_REDIRECT_URL = f"{BASE_URL}/api/dashboard/"         # where to go after login
ACCOUNT_LOGOUT_REDIRECT_URL = f"{BASE_URL}/api/docs/" 
ACCOUNT_EMAIL_VERIFICATION = "none"  # for dev; tighten later
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_REQUIRED = True

# Strongly recommended: use environment variables in production
# Google OAuth credentials from environment variables
GOOGLE_CLIENT_ID = os.getenv('client_id', '')
GOOGLE_CLIENT_SECRET = os.getenv('secret', '')

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": GOOGLE_CLIENT_ID,
            "secret": GOOGLE_CLIENT_SECRET,
            "key": "", 
            "response_type": "code", # usually blank
        },
        "SCOPE": [
            "profile",
            "email",
            # add more if you want to call Google APIs, e.g.:
            # "https://www.googleapis.com/auth/calendar.readonly",
        ],
        "AUTH_PARAMS": { "access_type": "offline", "prompt": "consent" },  # ensures refresh_token
    }
}

# Configure ALLOWED_HOSTS for production
# Detect if running on Render
IS_RENDER = os.getenv('RENDER', '').lower() == 'true'
# Detect if running on Heroku (for backward compatibility)
IS_HEROKU = "DYNO" in os.environ

if IS_RENDER:
    # Running on Render
    RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME', '')
    if RENDER_EXTERNAL_HOSTNAME:
        ALLOWED_HOSTS = [RENDER_EXTERNAL_HOSTNAME]
    # Also allow custom domain if set
    custom_domain = os.getenv('CUSTOM_DOMAIN', '')
    if custom_domain:
        ALLOWED_HOSTS.append(custom_domain)
    # Fallback to wildcard if no hostname is set
    if not ALLOWED_HOSTS:
        ALLOWED_HOSTS = ['*']
elif IS_HEROKU:
    # Running on Heroku (backward compatibility)
    ALLOWED_HOSTS = [
        os.getenv('HEROKU_APP_NAME', '') + '.herokuapp.com',
        os.getenv('CUSTOM_DOMAIN', ''),
    ]
    # Remove empty strings
    ALLOWED_HOSTS = [host for host in ALLOWED_HOSTS if host]
    # If no app name is set, allow all herokuapp.com subdomains
    if not ALLOWED_HOSTS:
        ALLOWED_HOSTS = ['*']
elif not DEBUG:
    # Production but not Render/Heroku
    ALLOWED_HOSTS = [
        os.getenv('CUSTOM_DOMAIN', ''),
    ]
    ALLOWED_HOSTS = [host for host in ALLOWED_HOSTS if host]
else:
    # During local dev
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]